name: Deploy
on:
  push:
    branches:
      - main
      
jobs:
  deploy_image:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build_image_step.outputs.image_tag }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Docker buildx Builder
        uses: docker/setup-buildx-action@v2
      - name: Build, tag, and push image
        id: build_image_step
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t markwryan/plex-audioscrobble-webhook:latest --push .
